ALTER TABLE "memory_items" ADD COLUMN IF NOT EXISTS "location_name" VARCHAR(255);
ALTER TABLE "memory_items" ADD COLUMN IF NOT EXISTS "latitude" DOUBLE PRECISION;
ALTER TABLE "memory_items" ADD COLUMN IF NOT EXISTS "longitude" DOUBLE PRECISION;